service: serverless-csv-sftp-http-endpoint
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  exportCSV:
    handler: src/handler.exportCSV
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline